name: splash_view
description: A splash view is the first screen the user sees when the application is launched.
version: 2.0.0
homepage: https://rahulchouhan.me
repository: https://github.com/chouhan-rahul/splash_view

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
